server:
  port: 8081
  
spring:

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/algafood?useSSL=false&createDatabaseIfNotExist=FALSE&allowPublicKeyRetrieval=TRUE&useTimezone=TRUE&serverTimezone=UTC
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
